### ISSUE TITLE
Development status of this project?

### ISSUE THREAD

**Issue by shulist** [QTodoTxt/QTodoTxt2#105]
Is this project still under active development. It seems the update dates are mostly far in the past. If it is NOT could anyone recommend a linux client GUI that is still active?

**Comment by topas-rec** [comment]
There is less development since the version two (that's just my opinion) but:

- The second version is stable and usable
- Still has development though it is not so much at the moment
- I use version two for my daily personal stuff
- If possible join in and help fixing some (in my opinion: minor) issues ☺

For me this application is the best cross platform todotxt app I know. (Most important for me is that it supports recurring tasks - which others don't)

**Comment by oroulet** [comment]
Not much activity for now but the foundation is correct and uses modern technology. So it is just a question of having someone with an itch to scratch and the development will start again..

**Comment by oroulet** [comment]
The guy who wrote the qml code seems to work on other things for now and I admit that I do not really understand that code..

**Comment by topas-rec** [comment]
I don't have the time to develop this any further at the moment. To give people a feedback who are making pull request we should clearly state the development status of this project either in this issue or on the landing page (readme file).

Is someone of the project owners able to continue this project? If not I would like to clearly state this in the readme and invite project maintainers.
