### ISSUE TITLE
How to build a Windows Installer?

### ISSUE THREAD

**Issue by jnstllng** [QTodoTxt/QTodoTxt2#110]
I already struggled in builkding a Windows Installer for QTodoTxt, no it happens also for QTodoTxt2. Is there already somethings thta can be used?
When I just run it with my Python installation, it does not integrate nicely in the taskbar...

**Comment by topas-rec** [comment]
I also tried to make a windows installer last week because I don't like the mentioned approach in the version 2 readme. It is a big bunch of data one has to download and it is complicated. Did you tried that BTW? (Does it fixes your problem)

Since the rewrite for version 2 the py2exe approach from version 1 does not work anymore. There is apy2exe version for python 3 that we might use.

**Comment by topas-rec** [comment]
Can you try the installer I made recently?
There are issues inside the app. Please ignore them. I would like to know if the app itself can be installed and starts properly.

Find the installer here and a portable version, too.
https://github.com/QTodoTxt/QTodoTxt2/releases/tag/2.0.0

**Comment by topas-rec** [comment]
Thanks for verifying that the installer works not only on my machine.
